---
  hosts: all
  gather_facts: no
  tasks:
    win_updates:
      category_names:
        - CriticalUpdates
        - SecurityUpdates
      whitelist:
        - KB4576750
    reboot: yes
    reboot_timeout: 1000
