---
  hosts: all
  gather_facts: no
  tasks:
	- name: Install Selected security, critical  updates without a scheduled task
    win_updates:
      category_names:
        - CriticalUpdates
        - SecurityUpdates
      whitelist:
        - KB4576750
	state: installed
    reboot: yes
    reboot_timeout: 1000
