---
- hosts: all
  gather_facts: no
  tasks:
  - name: Install only particular updates based on the KB numbers
   win_updates:
    - SecurityUpdates
    whitelist:
        - KB4576750
      log_path: C:\Temp\ansible-windows-update.txt
      state: installed
      reboot: yes
      reboot_timeout: 1000
