---
- hosts: Win
  become: yes
  become_method: runas
  become_user: dparmar@ODYSOLVD.COM
  become_password: Kahonakaho@123
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  tasks:
  
  - name: Copy a single file where the source is on the remote host
    ansible.windows.win_copy:
      src: \\odysolbn.ODYSOLVD.COM\c$\Test\windows10.0-kb4589210-v2-x64_bbbf54336d6e22da5de8d63891401d8f6077d2ce.msu
      dest: C:\temp\
      remote_src: true
