---
- hosts: Win
  tasks:

  - name: Install hotfix without validating the KB and Identifier
    community.windows.win_hotfix:
      source: C:\Temp\windows10.0-kb4598229-x86_dd943c5d69d146026f29d2cbe9e01c239c6ea56d.msu
      state: present
    register: hotfix_install
