---
- hosts: all
  gather_facts: no
  tasks:
  - name: Install all security, critical and rollup updates without a scheduled task
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
       whitelist:
        - KB4576750
      log_path: C:\Temp\ansible-windows-update.txt
      state: installed
      reboot: yes
      reboot_timeout: 1000
