---
- hosts: Win
  tasks:

  - name: Validate that the netlogon service has started, before running the next task
    ansible.windows.win_reboot:
    test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
