
---
- hosts: all
  gather_facts: no
  tasks:
  - name: Install all security, critical and rollup updates without a scheduled task
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      - UpdateRollups
      whitelist:
      - KB4576750
      - KB4571694
      log_path: C:\ansible-windows-update.txt
      state: installed
      reboot: yes
