---
- hosts: WindowServer2016-1
  gather_facts: no
  tasks:
    win_updates:
      category_names:
        - CriticalUpdates
        - SecurityUpdates
      whitelist:
        - KB4576750
    state: installed
    reboot: yes
    reboot_timeout: 1000
