---
- hosts: Win
  tasks:

  - name: Copy a single file where the source is on the remote host
    ansible.windows.win_copy:
      src: \\ODYSOLBN.odysol.com\Test\"*"
      dest: C:\temp\"*"
      remote_src: yes
